queue:
  name: Hosted VS2017
  demands: npm

trigger:
 - master

variables:
  ExtensionId: CLG-ParameterXmlValidation
  PackageId: chrisgardner

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/task.json'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)'
    targetFiles: '**/task.json'

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Create Package -Private'
  inputs:
    rootFolder: Extension
    outputPath: '$(Build.ArtifactStagingDirectory)\vsix'
    publisherId: '$(PackageID)'
    extensionId: '$(ExtensionID)'
    extensionTag: '-DEV'
    extensionVersion: '$(GitVersion.MajorMinorPatch)'
    updateTasksVersion: true
    extensionVisibility: private


- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Create Package -Public'
  inputs:
    rootFolder: Extension
    outputPath: '$(Build.ArtifactStagingDirectory)\vsix'
    publisherId: '$(PackageID)'
    extensionId: '$(ExtensionID)'
    extensionVersion: '$(GitVersion.MajorMinorPatch)'
    updateTasksVersion: true
    extensionVisibility: public

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: vsix'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\vsix'
    ArtifactName: vsix
